import { Job } from '@/app/jobs/page';

// Import internship type from internships page
export interface Internship {
    id: number;
    title: string;
    company: string;
    location: string;
    duration: string;
    stipend?: string;
    jobType: string;
    employmentType: string;
    skills: string[];
    postedDate: string;
    description: string;
    isRemote: boolean;
    isFeatured: boolean;
    isUrgent?: boolean;
    applicantCount?: number;
    companyLogo?: string;
    companySize?: string;
    industry?: string;
    benefits?: string[];
    companyType?: 'Startup' | 'MNC' | 'Product' | 'Service';
    startDate?: string;
    applicationDeadline?: string;
    isPartTime?: boolean;
    isPaid?: boolean;
    certificateProvided?: boolean;
    mentorshipIncluded?: boolean;
}

export const mockJobs: Job[] = [
    {
        id: 1,
        title: 'Frontend Developer',
        company: 'Swiggy',
        location: 'Bangalore, India',
        experienceRequired: '0-2 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['React', 'TypeScript', 'JavaScript', 'CSS', 'Redux'],
        postedDate: '2024-01-15',
        salary: '₹6-10 LPA',
        description:
            'Join our team to build amazing user interfaces for millions of food lovers...',
        isRemote: false,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 234,
        companyLogo: '/logos/swiggy.png',
        companySize: '5000-10000',
        industry: 'Food Tech',
        benefits: ['Health Insurance', 'Free Meals', 'Flexible Hours', 'Stock Options'],
        companyType: 'Startup',
    },
    {
        id: 2,
        title: 'Backend Engineer',
        company: 'Zomato',
        location: 'Gurgaon, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Java', 'Spring Boot', 'AWS', 'MySQL', 'Microservices'],
        postedDate: '2024-01-14',
        salary: '₹8-15 LPA',
        description: 'Build scalable backend systems for food delivery platform...',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 189,
        companyLogo: '/logos/zomato.png',
        companySize: '1000-5000',
        industry: 'Food Tech',
        benefits: ['Health Insurance', 'Work from Home', 'Learning Budget', 'Team Outings'],
        companyType: 'Startup',
    },
    {
        id: 3,
        title: 'Full Stack Developer',
        company: 'Paytm',
        location: 'Noida, India',
        experienceRequired: '2-4 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['React', 'Node.js', 'MongoDB', 'Express', 'Payment APIs'],
        postedDate: '2024-01-13',
        salary: '₹12-20 LPA',
        description: 'Work on cutting-edge fintech applications...',
        isRemote: false,
        isFeatured: false,
        isUrgent: true,
        applicantCount: 456,
        companyLogo: '/logos/paytm.png',
        companySize: '10000+',
        industry: 'Fintech',
        benefits: ['Health Insurance', 'Bonus', 'Cab Facility', 'Gym Membership'],
        companyType: 'MNC',
    },
    {
        id: 4,
        title: 'Data Scientist',
        company: 'Flipkart',
        location: 'Bangalore, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Python', 'Machine Learning', 'SQL', 'Pandas', 'TensorFlow'],
        postedDate: '2024-01-12',
        salary: '₹10-18 LPA',
        description: 'Analyze data to drive business decisions for e-commerce platform...',
        isRemote: true,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 312,
        companyLogo: '/logos/flipkart.png',
        companySize: '10000+',
        industry: 'E-commerce',
        benefits: ['Health Insurance', 'Stock Options', 'Learning Budget', 'Flexible Hours'],
        companyType: 'MNC',
    },
    {
        id: 5,
        title: 'UI/UX Designer',
        company: 'Ola',
        location: 'Bangalore, India',
        experienceRequired: '0-2 years',
        jobType: 'Full-time',
        employmentType: 'Contract',
        skills: ['Figma', 'Adobe XD', 'Photoshop', 'User Research', 'Prototyping'],
        postedDate: '2024-01-11',
        salary: '₹5-9 LPA',
        description: 'Design beautiful and intuitive user experiences for mobility platform...',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 167,
        companyLogo: '/logos/ola.png',
        companySize: '1000-5000',
        industry: 'Transportation',
        benefits: ['Health Insurance', 'Free Rides', 'Team Events', 'Learning Budget'],
        companyType: 'Startup',
    },
    {
        id: 6,
        title: 'DevOps Engineer',
        company: 'PhonePe',
        location: 'Bangalore, India',
        experienceRequired: '2-5 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Terraform'],
        postedDate: '2024-01-10',
        salary: '₹15-25 LPA',
        description: 'Manage and optimize cloud infrastructure for digital payments...',
        isRemote: true,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 89,
        companyLogo: '/logos/phonepe.png',
        companySize: '1000-5000',
        industry: 'Fintech',
        benefits: ['Health Insurance', 'Stock Options', 'Work from Home', 'Bonus'],
        companyType: 'Product',
    },
    {
        id: 7,
        title: 'Mobile App Developer',
        company: 'Dream11',
        location: 'Mumbai, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['React Native', 'Flutter', 'iOS', 'Android', 'Firebase'],
        postedDate: '2024-01-09',
        salary: '₹8-14 LPA',
        description: 'Build engaging mobile experiences for fantasy sports platform...',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 278,
        companyLogo: '/logos/dream11.png',
        companySize: '500-1000',
        industry: 'Gaming',
        benefits: ['Health Insurance', 'Game Credits', 'Team Outings', 'Flexible Hours'],
        companyType: 'Startup',
    },
    {
        id: 8,
        title: 'Blockchain Developer',
        company: 'CoinDCX',
        location: 'Mumbai, India',
        experienceRequired: '2-4 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Solidity', 'Web3.js', 'Ethereum', 'Smart Contracts', 'Node.js'],
        postedDate: '2024-01-08',
        salary: '₹18-30 LPA',
        description: 'Develop blockchain solutions for cryptocurrency exchange...',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 45,
        companyLogo: '/logos/coindcx.png',
        companySize: '100-500',
        industry: 'Cryptocurrency',
        benefits: ['Health Insurance', 'Crypto Bonus', 'Work from Home', 'Learning Budget'],
        companyType: 'Startup',
    },
    {
        id: 9,
        title: 'AI/ML Engineer',
        company: 'Hotstar',
        location: 'Bangalore, India',
        experienceRequired: '3-5 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision', 'NLP'],
        postedDate: '2024-01-07',
        salary: '₹20-35 LPA',
        description: 'Build AI-powered recommendation systems for streaming platform...',
        isRemote: false,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 123,
        companyLogo: '/logos/hotstar.png',
        companySize: '1000-5000',
        industry: 'Entertainment',
        benefits: ['Health Insurance', 'Stock Options', 'Content Access', 'Learning Budget'],
        companyType: 'MNC',
    },
    {
        id: 10,
        title: 'Cybersecurity Analyst',
        company: 'Razorpay',
        location: 'Bangalore, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Incident Response'],
        postedDate: '2024-01-06',
        salary: '₹12-20 LPA',
        description: 'Secure payment infrastructure and protect against cyber threats...',
        isRemote: true,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 156,
        companyLogo: '/logos/razorpay.png',
        companySize: '1000-5000',
        industry: 'Fintech',
        benefits: ['Health Insurance', 'Stock Options', 'Work from Home', 'Security Training'],
        companyType: 'Product',
    },
    {
        id: 11,
        title: 'Product Manager',
        company: "Byju's",
        location: 'Bangalore, India',
        experienceRequired: '3-6 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Product Strategy', 'Analytics', 'User Research', 'Agile', 'SQL'],
        postedDate: '2024-01-05',
        salary: '₹25-40 LPA',
        description: 'Lead product development for educational technology platform...',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 89,
        companyLogo: '/logos/byjus.png',
        companySize: '10000+',
        industry: 'EdTech',
        benefits: ['Health Insurance', 'Learning Budget', 'Flexible Hours', 'Stock Options'],
        companyType: 'Startup',
    },
    {
        id: 12,
        title: 'Cloud Architect',
        company: 'Freshworks',
        location: 'Chennai, India',
        experienceRequired: '5+ years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['AWS', 'Azure', 'GCP', 'Microservices', 'Kubernetes', 'Terraform'],
        postedDate: '2024-01-04',
        salary: '₹30-50 LPA',
        description: 'Design and implement cloud solutions for SaaS platform...',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 67,
        companyLogo: '/logos/freshworks.png',
        companySize: '1000-5000',
        industry: 'SaaS',
        benefits: ['Health Insurance', 'Stock Options', 'Work from Home', 'Learning Budget'],
        companyType: 'Product',
    },
];

// Mock Internship Data - 15 diverse internships from major Indian companies
export const mockInternships: Internship[] = [
    {
        id: 1,
        title: 'Frontend Development Intern',
        company: 'Swiggy',
        location: 'Bangalore, India',
        duration: '3 months',
        stipend: '₹25,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['React', 'JavaScript', 'HTML', 'CSS', 'Git'],
        postedDate: '2024-01-15',
        description:
            'Work on user-facing features for our food delivery platform. You will collaborate with our design and backend teams to create seamless user experiences that delight millions of customers. This internship offers hands-on experience with modern frontend technologies and the opportunity to work on real-world projects that impact millions of users daily.',
        isRemote: false,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 156,
        companyLogo: '/logos/swiggy.png',
        companySize: '5000-10000',
        industry: 'Food Tech',
        benefits: ['Mentorship', 'Free Meals', 'Certificate', 'Pre-placement Offer'],
        companyType: 'Startup',
        startDate: '2024-02-01',
        applicationDeadline: '2024-01-25',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 2,
        title: 'Backend Development Intern',
        company: 'Zomato',
        location: 'Gurgaon, India',
        duration: '6 months',
        stipend: '₹30,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Java', 'Spring Boot', 'MySQL', 'REST APIs', 'Git'],
        postedDate: '2024-01-14',
        description:
            'Build scalable backend services for restaurant discovery platform. You will work on microservices architecture, API development, and database optimization. This role offers exposure to high-scale systems handling millions of requests daily and the opportunity to learn from experienced engineers.',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 203,
        companyLogo: '/logos/zomato.png',
        companySize: '1000-5000',
        industry: 'Food Tech',
        benefits: ['Work from Home', 'Mentorship', 'Certificate', 'Learning Budget'],
        companyType: 'Startup',
        startDate: '2024-02-15',
        applicationDeadline: '2024-01-30',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 3,
        title: 'Data Science Intern',
        company: 'Flipkart',
        location: 'Bangalore, India',
        duration: '4 months',
        stipend: '₹35,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Python', 'Machine Learning', 'SQL', 'Pandas', 'Jupyter'],
        postedDate: '2024-01-13',
        description:
            'Analyze customer data to improve recommendation systems and enhance user experience. Work with large datasets, build predictive models, and contribute to data-driven decision making. You will gain experience in machine learning, statistical analysis, and big data technologies.',
        isRemote: false,
        isFeatured: false,
        isUrgent: true,
        applicantCount: 289,
        companyLogo: '/logos/flipkart.png',
        companySize: '10000+',
        industry: 'E-commerce',
        benefits: ['Health Insurance', 'Mentorship', 'Certificate', 'Gym Access'],
        companyType: 'MNC',
        startDate: '2024-03-01',
        applicationDeadline: '2024-02-10',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 4,
        title: 'UI/UX Design Intern',
        company: 'Ola',
        location: 'Bangalore, India',
        duration: '3 months',
        stipend: '₹20,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research', 'Wireframing'],
        postedDate: '2024-01-12',
        description:
            'Design intuitive user experiences for mobility solutions. Work on user research, wireframing, prototyping, and visual design. You will collaborate with product managers and developers to create user-centered designs that solve real-world transportation challenges.',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 134,
        companyLogo: '/logos/ola.png',
        companySize: '1000-5000',
        industry: 'Transportation',
        benefits: ['Free Rides', 'Design Tools Access', 'Certificate', 'Portfolio Review'],
        companyType: 'Startup',
        startDate: '2024-02-20',
        applicationDeadline: '2024-02-05',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 5,
        title: 'Mobile App Development Intern',
        company: 'Dream11',
        location: 'Mumbai, India',
        duration: '5 months',
        stipend: '₹28,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['React Native', 'Flutter', 'Android', 'iOS', 'Firebase'],
        postedDate: '2024-01-11',
        description:
            'Develop mobile features for fantasy sports platform. Work on cross-platform mobile applications, implement new features, and optimize app performance. You will gain experience in mobile development best practices and work with millions of active users.',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 178,
        companyLogo: '/logos/dream11.png',
        companySize: '500-1000',
        industry: 'Gaming',
        benefits: ['Game Credits', 'Team Events', 'Certificate', 'Device Access'],
        companyType: 'Startup',
        startDate: '2024-03-15',
        applicationDeadline: '2024-02-28',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 6,
        title: 'DevOps Intern',
        company: 'PhonePe',
        location: 'Bangalore, India',
        duration: '6 months',
        stipend: '₹40,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Linux'],
        postedDate: '2024-01-10',
        description:
            'Learn cloud infrastructure management for fintech platform. Work on containerization, CI/CD pipelines, monitoring, and automation. You will gain hands-on experience with cloud technologies and learn how to manage infrastructure at scale for financial services.',
        isRemote: true,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 92,
        companyLogo: '/logos/phonepe.png',
        companySize: '1000-5000',
        industry: 'Fintech',
        benefits: ['Work from Home', 'Cloud Credits', 'Certificate', 'Full-time Offer'],
        companyType: 'Product',
        startDate: '2024-02-10',
        applicationDeadline: '2024-01-28',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 7,
        title: 'Content Writing Intern',
        company: "Byju's",
        location: 'Bangalore, India',
        duration: '4 months',
        stipend: '₹15,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Content Writing', 'SEO', 'Research', 'Editing', 'WordPress'],
        postedDate: '2024-01-09',
        description:
            'Create engaging educational content for learning platform. Write blog posts, course descriptions, marketing copy, and educational materials. You will work with subject matter experts and learn about content strategy, SEO optimization, and educational content creation.',
        isRemote: true,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 245,
        companyLogo: '/logos/byjus.png',
        companySize: '10000+',
        industry: 'EdTech',
        benefits: ['Work from Home', 'Learning Access', 'Certificate', 'Writing Tools'],
        companyType: 'Startup',
        startDate: '2024-03-01',
        applicationDeadline: '2024-02-15',
        isPartTime: true,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: false,
    },
    {
        id: 8,
        title: 'Digital Marketing Intern',
        company: 'Paytm',
        location: 'Noida, India',
        duration: '3 months',
        stipend: '₹18,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Digital Marketing', 'Google Ads', 'Social Media', 'Analytics', 'SEO'],
        postedDate: '2024-01-08',
        description:
            'Drive user acquisition campaigns for fintech products. Work on social media marketing, paid advertising, content marketing, and analytics. You will learn about digital marketing strategies, campaign optimization, and performance measurement in the fintech industry.',
        isRemote: false,
        isFeatured: false,
        isUrgent: true,
        applicantCount: 167,
        companyLogo: '/logos/paytm.png',
        companySize: '10000+',
        industry: 'Fintech',
        benefits: ['Marketing Tools', 'Campaign Budget', 'Certificate', 'Networking'],
        companyType: 'MNC',
        startDate: '2024-02-25',
        applicationDeadline: '2024-02-10',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 9,
        title: 'AI/ML Research Intern',
        company: 'Hotstar',
        location: 'Bangalore, India',
        duration: '6 months',
        stipend: '₹45,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision', 'Research'],
        postedDate: '2024-01-07',
        description:
            'Research and develop AI models for content recommendation and personalization. Work on machine learning algorithms, deep learning models, and research projects. You will contribute to cutting-edge AI research and work with large-scale data from millions of users.',
        isRemote: false,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 78,
        companyLogo: '/logos/hotstar.png',
        companySize: '1000-5000',
        industry: 'Entertainment',
        benefits: ['Research Papers', 'GPU Access', 'Certificate', 'Conference Tickets'],
        companyType: 'MNC',
        startDate: '2024-03-10',
        applicationDeadline: '2024-02-20',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 10,
        title: 'Cybersecurity Intern',
        company: 'Razorpay',
        location: 'Bangalore, India',
        duration: '4 months',
        stipend: '₹32,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Python', 'Linux'],
        postedDate: '2024-01-06',
        description:
            'Learn security practices for payment infrastructure. Work on vulnerability assessments, security monitoring, incident response, and security tool development. You will gain experience in cybersecurity best practices and learn how to protect financial systems.',
        isRemote: true,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 89,
        companyLogo: '/logos/razorpay.png',
        companySize: '1000-5000',
        industry: 'Fintech',
        benefits: ['Security Training', 'Certification Vouchers', 'Certificate', 'Tools Access'],
        companyType: 'Product',
        startDate: '2024-02-28',
        applicationDeadline: '2024-02-12',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 11,
        title: 'Product Management Intern',
        company: 'Freshworks',
        location: 'Chennai, India',
        duration: '5 months',
        stipend: '₹35,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Product Strategy', 'Analytics', 'User Research', 'Wireframing', 'SQL'],
        postedDate: '2024-01-05',
        description:
            'Support product development for SaaS platform. Work on product strategy, user research, feature planning, and data analysis. You will learn about product management methodologies, customer development, and how to build products that customers love.',
        isRemote: true,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 123,
        companyLogo: '/logos/freshworks.png',
        companySize: '1000-5000',
        industry: 'SaaS',
        benefits: ['Product Tools', 'Customer Calls', 'Certificate', 'PM Mentorship'],
        companyType: 'Product',
        startDate: '2024-03-05',
        applicationDeadline: '2024-02-18',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 12,
        title: 'Blockchain Development Intern',
        company: 'CoinDCX',
        location: 'Mumbai, India',
        duration: '4 months',
        stipend: '₹38,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Solidity', 'Web3.js', 'Ethereum', 'Smart Contracts', 'JavaScript'],
        postedDate: '2024-01-04',
        description:
            'Develop blockchain solutions for crypto exchange platform. Work on smart contracts, DeFi protocols, and blockchain integrations. You will learn about cryptocurrency technologies, blockchain development, and decentralized finance applications.',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 45,
        companyLogo: '/logos/coindcx.png',
        companySize: '100-500',
        industry: 'Cryptocurrency',
        benefits: ['Crypto Learning', 'Testnet Access', 'Certificate', 'Blockchain Tools'],
        companyType: 'Startup',
        startDate: '2024-02-15',
        applicationDeadline: '2024-02-01',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 13,
        title: 'Quality Assurance Intern',
        company: 'Myntra',
        location: 'Bangalore, India',
        duration: '3 months',
        stipend: '₹22,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Manual Testing', 'Automation Testing', 'Selenium', 'API Testing', 'Bug Tracking'],
        postedDate: '2024-01-03',
        description:
            'Ensure quality of fashion e-commerce platform through comprehensive testing. Work on manual testing, test automation, API testing, and quality assurance processes. You will learn about software testing methodologies and quality assurance best practices.',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 156,
        companyLogo: '/logos/myntra.png',
        companySize: '1000-5000',
        industry: 'E-commerce',
        benefits: ['Testing Tools', 'Fashion Discounts', 'Certificate', 'QA Training'],
        companyType: 'MNC',
        startDate: '2024-03-01',
        applicationDeadline: '2024-02-14',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 14,
        title: 'Business Analyst Intern',
        company: 'Urban Company',
        location: 'Gurgaon, India',
        duration: '4 months',
        stipend: '₹26,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Excel', 'SQL', 'Data Analysis', 'Business Intelligence', 'Tableau'],
        postedDate: '2024-01-02',
        description:
            'Analyze business metrics for home services platform. Work on data analysis, business intelligence, market research, and process optimization. You will learn about business analysis methodologies and how data drives business decisions.',
        isRemote: false,
        isFeatured: false,
        isUrgent: true,
        applicantCount: 198,
        companyLogo: '/logos/urbancompany.png',
        companySize: '1000-5000',
        industry: 'Services',
        benefits: ['Service Credits', 'Analytics Tools', 'Certificate', 'Business Training'],
        companyType: 'Startup',
        startDate: '2024-02-20',
        applicationDeadline: '2024-02-05',
        isPartTime: false,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: true,
    },
    {
        id: 15,
        title: 'HR Intern',
        company: 'Nykaa',
        location: 'Mumbai, India',
        duration: '3 months',
        stipend: '₹18,000/month',
        jobType: 'Internship',
        employmentType: 'Temporary',
        skills: ['Recruitment', 'HR Operations', 'Communication', 'MS Office', 'LinkedIn'],
        postedDate: '2024-01-01',
        description:
            'Support talent acquisition for beauty e-commerce platform. Work on recruitment, employee onboarding, HR operations, and talent management. You will learn about human resources best practices and gain experience in talent acquisition.',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 234,
        companyLogo: '/logos/nykaa.png',
        companySize: '1000-5000',
        industry: 'E-commerce',
        benefits: ['Beauty Products', 'HR Tools', 'Certificate', 'Networking Events'],
        companyType: 'Startup',
        startDate: '2024-03-01',
        applicationDeadline: '2024-02-15',
        isPartTime: true,
        isPaid: true,
        certificateProvided: true,
        mentorshipIncluded: false,
    },
];

export const findJobBySlug = (companySlug: string, jobTitleSlug: string): Job | null => {
    return (
        mockJobs.find((job) => {
            const jobCompanySlug = job.company
                .toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/[^a-z0-9-]/g, '');
            const jobTitleSlugMatch = job.title
                .toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/[^a-z0-9-]/g, '');
            return jobCompanySlug === companySlug && jobTitleSlugMatch === jobTitleSlug;
        }) || null
    );
};

export const findInternshipBySlug = (
    companySlug: string,
    internshipTitleSlug: string,
): Internship | null => {
    return (
        mockInternships.find((internship) => {
            const internshipCompanySlug = internship.company
                .toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/[^a-z0-9-]/g, '');
            const internshipTitleSlugMatch = internship.title
                .toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/[^a-z0-9-]/g, '');
            return (
                internshipCompanySlug === companySlug &&
                internshipTitleSlugMatch === internshipTitleSlug
            );
        }) || null
    );
};
