import { Job } from '@/app/jobs/page';

export const mockJobs: Job[] = [
    {
        id: 1,
        title: 'Frontend Developer',
        company: 'Swiggy',
        location: 'Bangalore, India',
        experienceRequired: '0-2 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['React', 'TypeScript', 'JavaScript', 'CSS', 'Redux'],
        postedDate: '2024-01-15',
        salary: '₹6-10 LPA',
        description:
            'Join our team to build amazing user interfaces for millions of food lovers...',
        isRemote: false,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 234,
        companyLogo: '/logos/swiggy.png',
        companySize: '5000-10000',
        industry: 'Food Tech',
        benefits: ['Health Insurance', 'Free Meals', 'Flexible Hours', 'Stock Options'],
        companyType: 'Startup',
    },
    {
        id: 2,
        title: 'Backend Engineer',
        company: 'Zomato',
        location: 'Gurgaon, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Java', 'Spring Boot', 'AWS', 'MySQL', 'Microservices'],
        postedDate: '2024-01-14',
        salary: '₹8-15 LPA',
        description: 'Build scalable backend systems for food delivery platform...',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 189,
        companyLogo: '/logos/zomato.png',
        companySize: '1000-5000',
        industry: 'Food Tech',
        benefits: ['Health Insurance', 'Work from Home', 'Learning Budget', 'Team Outings'],
        companyType: 'Startup',
    },
    {
        id: 3,
        title: 'Full Stack Developer',
        company: 'Paytm',
        location: 'Noida, India',
        experienceRequired: '2-4 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['React', 'Node.js', 'MongoDB', 'Express', 'Payment APIs'],
        postedDate: '2024-01-13',
        salary: '₹12-20 LPA',
        description: 'Work on cutting-edge fintech applications...',
        isRemote: false,
        isFeatured: false,
        isUrgent: true,
        applicantCount: 456,
        companyLogo: '/logos/paytm.png',
        companySize: '10000+',
        industry: 'Fintech',
        benefits: ['Health Insurance', 'Bonus', 'Cab Facility', 'Gym Membership'],
        companyType: 'MNC',
    },
    {
        id: 4,
        title: 'Data Scientist',
        company: 'Flipkart',
        location: 'Bangalore, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Python', 'Machine Learning', 'SQL', 'Pandas', 'TensorFlow'],
        postedDate: '2024-01-12',
        salary: '₹10-18 LPA',
        description: 'Analyze data to drive business decisions for e-commerce platform...',
        isRemote: true,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 312,
        companyLogo: '/logos/flipkart.png',
        companySize: '10000+',
        industry: 'E-commerce',
        benefits: ['Health Insurance', 'Stock Options', 'Learning Budget', 'Flexible Hours'],
        companyType: 'MNC',
    },
    {
        id: 5,
        title: 'UI/UX Designer',
        company: 'Ola',
        location: 'Bangalore, India',
        experienceRequired: '0-2 years',
        jobType: 'Full-time',
        employmentType: 'Contract',
        skills: ['Figma', 'Adobe XD', 'Photoshop', 'User Research', 'Prototyping'],
        postedDate: '2024-01-11',
        salary: '₹5-9 LPA',
        description: 'Design beautiful and intuitive user experiences for mobility platform...',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 167,
        companyLogo: '/logos/ola.png',
        companySize: '1000-5000',
        industry: 'Transportation',
        benefits: ['Health Insurance', 'Free Rides', 'Team Events', 'Learning Budget'],
        companyType: 'Startup',
    },
    {
        id: 6,
        title: 'DevOps Engineer',
        company: 'PhonePe',
        location: 'Bangalore, India',
        experienceRequired: '2-5 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Terraform'],
        postedDate: '2024-01-10',
        salary: '₹15-25 LPA',
        description: 'Manage and optimize cloud infrastructure for digital payments...',
        isRemote: true,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 89,
        companyLogo: '/logos/phonepe.png',
        companySize: '1000-5000',
        industry: 'Fintech',
        benefits: ['Health Insurance', 'Stock Options', 'Work from Home', 'Bonus'],
        companyType: 'Product',
    },
    {
        id: 7,
        title: 'Mobile App Developer',
        company: 'Dream11',
        location: 'Mumbai, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['React Native', 'Flutter', 'iOS', 'Android', 'Firebase'],
        postedDate: '2024-01-09',
        salary: '₹8-14 LPA',
        description: 'Build engaging mobile experiences for fantasy sports platform...',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 278,
        companyLogo: '/logos/dream11.png',
        companySize: '500-1000',
        industry: 'Gaming',
        benefits: ['Health Insurance', 'Game Credits', 'Team Outings', 'Flexible Hours'],
        companyType: 'Startup',
    },
    {
        id: 8,
        title: 'Blockchain Developer',
        company: 'CoinDCX',
        location: 'Mumbai, India',
        experienceRequired: '2-4 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Solidity', 'Web3.js', 'Ethereum', 'Smart Contracts', 'Node.js'],
        postedDate: '2024-01-08',
        salary: '₹18-30 LPA',
        description: 'Develop blockchain solutions for cryptocurrency exchange...',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 45,
        companyLogo: '/logos/coindcx.png',
        companySize: '100-500',
        industry: 'Cryptocurrency',
        benefits: ['Health Insurance', 'Crypto Bonus', 'Work from Home', 'Learning Budget'],
        companyType: 'Startup',
    },
    {
        id: 9,
        title: 'AI/ML Engineer',
        company: 'Hotstar',
        location: 'Bangalore, India',
        experienceRequired: '3-5 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision', 'NLP'],
        postedDate: '2024-01-07',
        salary: '₹20-35 LPA',
        description: 'Build AI-powered recommendation systems for streaming platform...',
        isRemote: false,
        isFeatured: true,
        isUrgent: true,
        applicantCount: 123,
        companyLogo: '/logos/hotstar.png',
        companySize: '1000-5000',
        industry: 'Entertainment',
        benefits: ['Health Insurance', 'Stock Options', 'Content Access', 'Learning Budget'],
        companyType: 'MNC',
    },
    {
        id: 10,
        title: 'Cybersecurity Analyst',
        company: 'Razorpay',
        location: 'Bangalore, India',
        experienceRequired: '1-3 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Incident Response'],
        postedDate: '2024-01-06',
        salary: '₹12-20 LPA',
        description: 'Secure payment infrastructure and protect against cyber threats...',
        isRemote: true,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 156,
        companyLogo: '/logos/razorpay.png',
        companySize: '1000-5000',
        industry: 'Fintech',
        benefits: ['Health Insurance', 'Stock Options', 'Work from Home', 'Security Training'],
        companyType: 'Product',
    },
    {
        id: 11,
        title: 'Product Manager',
        company: "Byju's",
        location: 'Bangalore, India',
        experienceRequired: '3-6 years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['Product Strategy', 'Analytics', 'User Research', 'Agile', 'SQL'],
        postedDate: '2024-01-05',
        salary: '₹25-40 LPA',
        description: 'Lead product development for educational technology platform...',
        isRemote: false,
        isFeatured: false,
        isUrgent: false,
        applicantCount: 89,
        companyLogo: '/logos/byjus.png',
        companySize: '10000+',
        industry: 'EdTech',
        benefits: ['Health Insurance', 'Learning Budget', 'Flexible Hours', 'Stock Options'],
        companyType: 'Startup',
    },
    {
        id: 12,
        title: 'Cloud Architect',
        company: 'Freshworks',
        location: 'Chennai, India',
        experienceRequired: '5+ years',
        jobType: 'Full-time',
        employmentType: 'Permanent',
        skills: ['AWS', 'Azure', 'GCP', 'Microservices', 'Kubernetes', 'Terraform'],
        postedDate: '2024-01-04',
        salary: '₹30-50 LPA',
        description: 'Design and implement cloud solutions for SaaS platform...',
        isRemote: true,
        isFeatured: true,
        isUrgent: false,
        applicantCount: 67,
        companyLogo: '/logos/freshworks.png',
        companySize: '1000-5000',
        industry: 'SaaS',
        benefits: ['Health Insurance', 'Stock Options', 'Work from Home', 'Learning Budget'],
        companyType: 'Product',
    },
];

export const findJobBySlug = (companySlug: string, jobTitleSlug: string): Job | null => {
    return (
        mockJobs.find((job) => {
            const jobCompanySlug = job.company
                .toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/[^a-z0-9-]/g, '');
            const jobTitleSlugMatch = job.title
                .toLowerCase()
                .replace(/\s+/g, '-')
                .replace(/[^a-z0-9-]/g, '');
            return jobCompanySlug === companySlug && jobTitleSlugMatch === jobTitleSlug;
        }) || null
    );
};
